name: stock_market_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  sizer: ^2.0.15
  dio: ^4.0.4
  get_storage: any
  url_launcher: ^6.0.18
  syncfusion_flutter_charts: ^19.4.48+1
  interactive_chart: ^0.3.4
  timeago: ^3.2.2
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  connectivity_plus: ^2.2.1
  package_info_plus: ^1.4.0
  facebook_audience_network: ^1.0.1
#  google_mobile_ads: ^1.1.0
  admob_flutter: ^2.0.0
  flutter_share: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/

